export const DISPLAY_ALERT = 'DISPLAY_ALERT';
export const CLOSE_ALERT = 'CLOSE_ALERT';
export const DISPLAY_SNACKBAR = 'DISPLAY_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const DISPLAY_MODAL_DIALOG = 'DISPLAY_MODAL_DIALOG';
export const CLOSE_MODAL_DIALOG = 'CLOSE_MODAL_DIALOG';
export const TOGGLE_APP_OVERLAY = 'TOGGLE_APP_OVERLAY';

export const FETCH_USER_ACCOUNT = 'FETCH_USER_ACCOUNT';

export const REAUTHORIZE_LOGIN = 'REAUTHORIZE_LOGIN';
export const LOGIN_BY_EMAIL = 'LOGIN_BY_EMAIL';
export const SIGNUP_BY_EMAIL = 'SIGNUP_BY_EMAIL';
export const TOGGLE_VIEW_SIGN_UP = 'TOGGLE_VIEW_SIGN_UP';
export const TOGGLE_LOGIN_MODAL = 'TOGGLE_LOGIN_MODAL';
export const SIGNUP_WITH_SOCIAL = 'SIGNUP_WITH_SOCIAL';
export const SET_LOGIN_ERROR_MESSAGE = 'SET_LOGIN_ERROR_MESSAGE';
export const GO_BACK_FROM_SIGN_UP_SUCCESS = 'GO_BACK_FROM_SIGN_UP_SUCCESS'
export const TOGGLE_SIGNUP_LOGIN = 'TOGGLE_SIGNUP_LOGIN'

export const FETCH_NEW_VEHICLE_STATIC_DATA =  'GET_NEW_VEHICLE_STATIC_DATA'
export const FETCH_VEHICLE_MAKES = 'GET_VEHICLE_MAKES';
export const FETCH_VEHICLE_MODELS = 'GET_VEHICLE_MODELS';

export const DELETE_LISTING = 'DELETE_LISTING';
export const FETCH_LISTING = 'FETCH_LISTING';
export const CLEAR_LISTING = 'CLEAR_LISTING';
export const FETCH_HOST_LISTINGS = 'FETCH_HOST_LISTINGS';

export const SET_LISTING_PROP = 'SET_LISTING_PROP';
export const SET_LISTING_VEHICLE_PROP = 'SET_LISTING_VEHICLE_PROP';
export const SET_LISTING_VEHICLE_REGISTRATION_PROP = 'SET_LISTING_VEHICLE_REGISTRATION_PROP';

export const SET_LISTING_VEHICLE_YEAR = 'SET_LISTING_VEHICLE_YEAR';
export const SET_LISTING_VEHICLE_MAKE = 'SET_LISTING_VEHICLE_MAKE';

export const SET_LISTING_ADVANCE_TIME = 'SET_LISTING_ADVANCE_TIME';
export const SET_LISTING_TRIP_MIN_DURATION = 'SET_LISTING_TRIP_MIN_DURATION';
export const SET_LISTING_TRIP_MAX_DURATION = 'SET_LISTING_TRIP_MAX_DURATION';

export const SET_LISTING_LOCATION = 'SET_LISTING_LOCATION';

export const SET_LISTING_GH_POSTAL_CODE = 'SET_LISTING_GH_POSTAL_CODE';

export const ADD_LISTING_PHOTO_FULFILLED = 'ADD_LISTING_PHOTO_FULFILLED';
export const SAVE_LISTING_PHOTO = 'SAVE_LISTING_PHOTO';
export const DELETE_LISTING_PHOTO = 'DELETE_LISTING_PHOTO';
export const PUBLISH_LISTING = 'PUBLISH_LISTING';

export const SAVE_LISTING_ELEGIBILITY = 'SAVE_LISTING_ELEGIBILITY';
export const SAVE_LISTING_AVAILABILITY = 'SAVE_LISTING_AVAILABILITY';
export const SAVE_LISTING_DETAILS = 'SAVE_LISTING_DETAILS';
export const SAVE_LISTING_PHOTOS_STAGE = 'SAVE_LISTING_PHOTOS_STAGE';

export const FETCH_PROFILE_DATA = 'FETCH_PROFILE_DATA'
export const TOGGLE_EDIT_PROFILE = 'TOGGLE_EDIT_PROFILE'
export const SET_ABOUT_TEXT = 'SET_ABOUT_TEXT';
export const SAVE_PROFILE_PICTURE = 'SAVE_PROFILE_PICTURE';
export const SAVE_COVER_PHOTO = 'SAVE_COVER_PHOTO';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const CLEAR_PROFILE_PAGE = 'CLEAR_PROFILE_PAGE';

export const SAVE_NEW_ACCOUNT = 'SAVE_NEW_ACCOUNT';
export const SAVE_NEW_ACCOUNT_DETAILS = 'SAVE_NEW_ACCOUNT_DETAILS';
export const ACTIVATE_NEW_ACCOUNT = 'ACTIVATE_NEW_ACCOUNT';
export const ACTIVATE_NEW_USER_ACCOUNT = 'ACTIVATE_NEW_USER_ACCOUNT';
export const VERIFY_RESET_ACCOUNT_PASSWORD = 'VERIFY_RESET_ACCOUNT_PASSWORD';
export const RESET_ACCOUNT_PASSWORD = 'RESET_ACCOUNT_PASSWORD';
export const TOGGLE_PASSWORD_RESET_FORM = 'TOGGLE_PASSWORD_RESET_FORM';
export const SEND_RESET_ACCOUNT_PASSWORD_EMAIL = 'SEND_RESET_ACCOUNT_PASSWORD_EMAIL';
export const UPDATE_NEW_ACCOUNT_DETAILS_PROP = 'UPDATE_NEW_ACCOUNT_DETAILS_PROP';
export const CLEAR_LOGIN_VIEW = 'CLEAR_LOGIN_VIEW';

export const SKIP_NEW_ACCOUNT_STEP = 'SKIP_NEW_ACCOUNT_STEP';
export const TRANSITION_PREV_NEW_ACCOUNT_STEP = 'TRANSITION_PREV_NEW_ACCOUNT_STEP';

export const FETCH_SEARCH_LISTINGS = 'FETCH_SEARCH_LISTINGS';
export const SET_SEARCH_LISTINGS_LOCATION = 'SET_SEARCH_LISTINGS_LOCATION';
export const CLEAR_SEARCH_LISTINGS = 'CLEAR_SEARCH_LISTINGS';
export const TOGGLE_SEARCH_LISTING_MODAL = 'TOGGLE_SEARCH_LISTING_MODAL';

export const LOG_OUT_USER = 'LOG_OUT_USER';

export const FETCH_GH_LOCATION_SEARCH_TAXONOMY = 'FETCH_GH_LOCATION_SEARCH_TAXONOMY';

export const SET_RESERVATION_START_DATE = 'SET_RESERVATION_START_DATE';
export const SET_RESERVATION_START_TIME = 'SET_RESERVATION_START_TIME';
export const SET_RESERVATION_END_DATE = 'SET_RESERVATION_END_DATE';
export const SET_RESERVATION_END_TIME = 'SET_RESERVATION_END_TIME';
export const SET_INITIAL_TRIP_DATES = 'SET_INITIAL_TRIP_DATES';
export const SET_INITIAL_RESERVATION_MESSAGE = 'SET_INITIAL_RESERVATION_MESSAGE';
export const SAVE_RESERVATION = 'SAVE_RESERVATION';
export const APPROVE_PENDING_RESERVATION = 'APPROVE_PENDING_RESERVATION';
export const FETCH_TRIPS = 'FETCH_TRIPS';
export const FETCH_TRIP_FEED = 'FETCH_TRIP_FEED';
export const START_TRIP = 'START_TRIP';
export const AUTHORIZE_START_TRIP = 'AUTHORIZE_START_TRIP';
export const DRIVER_END_TRIP = 'DRIVER_END_TRIP';
export const END_TRIP = 'END_TRIP';

export const GET_TRIP = 'GET_TRIP';
export const UPDATE_TRIP_STATUS = 'UPDATE_TRIP_STATUS';
export const SAVE_TRIP_PHOTO = 'SAVE_TRIP_PHOTO';
export const UPDATE_TRIP_PHOTO = 'UPDATE_TRIP_PHOTO';
export const SET_TRIP_PHOTO_DESCRIPTION = 'SET_TRIP_PHOTO_DESCRIPTION';
export const DELETE_TRIP_PHOTO = 'DELETE_TRIP_PHOTO';
export const DISPLAY_TRIP_PHOTO_MODAL = 'DISPLAY_TRIP_PHOTO_MODAL';
export const HIDE_TRIP_PHOTO_MODAL = 'HIDE_TRIP_PHOTO_MODAL';

export const TOGGLE_MESSAGE_INIT_VIEW = 'TOGGLE_MESSAGE_INIT_VIEW';
export const SET_MESSAGE_LIST_TAB = 'SET_MESSAGE_LIST_TAB';
export const GET_ALL_MESSAGES = 'GET_ALL_MESSAGES';
export const GET_RESERVATION = 'GET_RESERVATION';
export const SET_RESERVATION_MESSAGE_INIT = 'SET_RESERVATION_MESSAGE_INIT';
export const EDIT_NEW_MESSAGE = 'EDIT_NEW_MESSAGE';
export const CLEAR_RESERVATION_MESSAGES = 'CLEAR_RESERVATION_MESSAGES'
export const JOIN_MESSAGE_ROOM = 'JOIN_MESSAGE_ROOM'
export const REALTIME_SET_SOCKET_SESSION_ID = 'REALTIME_SET_SOCKET_SESSION_ID';
export const REALTIME_CONNECTED = 'REALTIME_CONNECTED';
export const REALTIME_UPDATE_IS_TYPING = 'REALTIME_UPDATE_IS_TYPING';
export const REALTIME_RECEIVE_ALL_MESSAGES = 'REALTIME_RECEIVE_ALL_MESSAGES';
export const REALTIME_RECEIVED_MESSAGE = 'REALTIME_RECEIVED_MESSAGE';
export const REALTIME_JOINED_ROOM = 'REALTIME_JOINED_ROOM';
export const REALTIME_RECEIVE_NOTIFICATIONS = 'REALTIME_RECEIVE_NOTIFICATIONS';
export const REALTIME_CLEAR_NOTIFICATIONS = 'REALTIME_CLEAR_NOTIFICATIONS';
export const REALTIME_RECEIVE_MESSAGE_NOTIFICATIONS = 'REALTIME_RECEIVE_MESSAGE_NOTIFICATIONS';
export const REALTIME_CLEAR_MESSAGE_NOTIFICATIONS = 'REALTIME_CLEAR_MESSAGE_NOTIFICATIONS';
export const REALTIME_RECEIVE_TRIP_MEETUP_SHARED_LOCATION = 'REALTIME_RECEIVE_TRIP_MEETUP_SHARED_LOCATION';

export const UPDATE_WEB_PUSH_SUBSCRIPTION = 'UPDATE_WEB_PUSH_SUBSCRIPTION';
export const TURN_ON_WEB_PUSH_NOTIFICATIONS = 'TURN_ON_WEB_PUSH_NOTIFICATIONS';
export const TURN_OFF_WEB_PUSH_NOTIFICATIONS = 'TURN_OFF_WEB_PUSH_NOTIFICATIONS';

export const UPDATE_USER_PROFILE_PICTURE = 'UPDATE_USER_PROFILE_PICTURE';

