export default {
  'A': {
    'region': 'Ashanti Region',
    'districts': {
      '2': 'North Gonja',
      '3': 'Central Gonja',
      '4': 'East Gonja',
      '5': 'West Gonja',
      '6': 'Offinso North',
      '7': 'Offinso South',
      '9': 'Bosome Freho Ext',
      'F': 'Sefwi Akontombra',
      'X': 'Wassa Amenfi East',
      'Y': 'Wassa Amenfi West',
      'V': 'Central Tongu',
      'W': 'Wassa Amenfi Central',
      'C': 'Bia East',
      'N': 'Nzema East',
      'A': 'Aowin',
      'S': 'Sekondi-Takoradi',
      'G': 'Sefwi Wiaso',
      'I': 'Ho West',
      'H': 'Ahanta West',
      'B': 'Bibiani/Anhwiaso/Bekwai',
      'T': 'Tarkwa Nsuaem',
      'E': 'Ellembelle',
      'J': 'Jomoro',
      'K': 'Keta',
      'U': 'Suaman',
      'D': 'Bia West',
      'M': 'Mpohor',
      'O': 'Bodi',
      'P': 'Prestea Huni Valley',
      'Q': 'Juaboso',
      'R': 'Shama',
      'Z': 'Wassa East',
      'L': 'Lawra'
    }
  },
  'B': {
    'region': 'Brong Ahafo',
    'districts': {
      '2': 'North Gonja',
      '3': 'Central Gonja',
      '4': 'East Gonja',
      '5': 'West Gonja',
      '6': 'Offinso North',
      '7': 'Offinso South',
      '9': 'Bosome Freho Ext',
      'F': 'Sefwi Akontombra',
      'X': 'Wassa Amenfi East',
      'Y': 'Wassa Amenfi West',
      'V': 'Central Tongu',
      'W': 'Wassa Amenfi Central',
      'C': 'Bia East',
      'N': 'Nzema East',
      'A': 'Aowin',
      'S': 'Sekondi-Takoradi',
      'G': 'Sefwi Wiaso',
      'I': 'Ho West',
      'H': 'Ahanta West',
      'B': 'Bibiani/Anhwiaso/Bekwai',
      'T': 'Tarkwa Nsuaem',
      'E': 'Ellembelle',
      'J': 'Jomoro',
      'K': 'Keta',
      'U': 'Suaman',
      'D': 'Bia West',
      'M': 'Mpohor',
      'O': 'Bodi',
      'P': 'Prestea Huni Valley',
      'Q': 'Juaboso',
      'R': 'Shama',
      'Z': 'Wassa East',
      'L': 'Lawra'
    }
  },
  'C': {
    'region': 'Central',
    'districts': {
      '2': 'North Gonja',
      '3': 'Central Gonja',
      '4': 'East Gonja',
      '5': 'West Gonja',
      '6': 'Offinso North',
      '7': 'Offinso South',
      '9': 'Bosome Freho Ext',
      'F': 'Sefwi Akontombra',
      'X': 'Wassa Amenfi East',
      'Y': 'Wassa Amenfi West',
      'V': 'Central Tongu',
      'W': 'Wassa Amenfi Central',
      'C': 'Bia East',
      'N': 'Nzema East',
      'A': 'Aowin',
      'S': 'Sekondi-Takoradi',
      'G': 'Sefwi Wiaso',
      'I': 'Ho West',
      'H': 'Ahanta West',
      'B': 'Bibiani/Anhwiaso/Bekwai',
      'T': 'Tarkwa Nsuaem',
      'E': 'Ellembelle',
      'J': 'Jomoro',
      'K': 'Keta',
      'U': 'Suaman',
      'D': 'Bia West',
      'M': 'Mpohor',
      'O': 'Bodi',
      'P': 'Prestea Huni Valley',
      'Q': 'Juaboso',
      'R': 'Shama',
      'Z': 'Wassa East',
      'L': 'Lawra'
    }
  },
  'E': {
    'region': 'Eastern',
    'districts': {
      '2': 'North Gonja',
      '3': 'Central Gonja',
      '4': 'East Gonja',
      '5': 'West Gonja',
      '6': 'Offinso North',
      '7': 'Offinso South',
      '9': 'Bosome Freho Ext',
      'F': 'Sefwi Akontombra',
      'X': 'Wassa Amenfi East',
      'Y': 'Wassa Amenfi West',
      'V': 'Central Tongu',
      'W': 'Wassa Amenfi Central',
      'C': 'Bia East',
      'N': 'Nzema East',
      'A': 'Aowin',
      'S': 'Sekondi-Takoradi',
      'G': 'Sefwi Wiaso',
      'I': 'Ho West',
      'H': 'Ahanta West',
      'B': 'Bibiani/Anhwiaso/Bekwai',
      'T': 'Tarkwa Nsuaem',
      'E': 'Ellembelle',
      'J': 'Jomoro',
      'K': 'Keta',
      'U': 'Suaman',
      'D': 'Bia West',
      'M': 'Mpohor',
      'O': 'Bodi',
      'P': 'Prestea Huni Valley',
      'Q': 'Juaboso',
      'R': 'Shama',
      'Z': 'Wassa East',
      'L': 'Lawra'
    }
  },
  'G': {
    'region': 'Greater Accra',
    'districts': {
      '2': 'North Gonja',
      '3': 'Central Gonja',
      '4': 'East Gonja',
      '5': 'West Gonja',
      '6': 'Offinso North',
      '7': 'Offinso South',
      '9': 'Bosome Freho Ext',
      'F': 'Sefwi Akontombra',
      'X': 'Wassa Amenfi East',
      'Y': 'Wassa Amenfi West',
      'V': 'Central Tongu',
      'W': 'Wassa Amenfi Central',
      'C': 'Bia East',
      'N': 'Nzema East',
      'A': 'Aowin',
      'S': 'Sekondi-Takoradi',
      'G': 'Sefwi Wiaso',
      'I': 'Ho West',
      'H': 'Ahanta West',
      'B': 'Bibiani/Anhwiaso/Bekwai',
      'T': 'Tarkwa Nsuaem',
      'E': 'Ellembelle',
      'J': 'Jomoro',
      'K': 'Keta',
      'U': 'Suaman',
      'D': 'Bia West',
      'M': 'Mpohor',
      'O': 'Bodi',
      'P': 'Prestea Huni Valley',
      'Q': 'Juaboso',
      'R': 'Shama',
      'Z': 'Wassa East',
      'L': 'Lawra'
    }
  },
  'N': {
    'region': 'Northern',
    'districts': {
      '2': 'North Gonja',
      '3': 'Central Gonja',
      '4': 'East Gonja',
      '5': 'West Gonja',
      '6': 'Offinso North',
      '7': 'Offinso South',
      '9': 'Bosome Freho Ext',
      'F': 'Sefwi Akontombra',
      'X': 'Wassa Amenfi East',
      'Y': 'Wassa Amenfi West',
      'V': 'Central Tongu',
      'W': 'Wassa Amenfi Central',
      'C': 'Bia East',
      'N': 'Nzema East',
      'A': 'Aowin',
      'S': 'Sekondi-Takoradi',
      'G': 'Sefwi Wiaso',
      'I': 'Ho West',
      'H': 'Ahanta West',
      'B': 'Bibiani/Anhwiaso/Bekwai',
      'T': 'Tarkwa Nsuaem',
      'E': 'Ellembelle',
      'J': 'Jomoro',
      'K': 'Keta',
      'U': 'Suaman',
      'D': 'Bia West',
      'M': 'Mpohor',
      'O': 'Bodi',
      'P': 'Prestea Huni Valley',
      'Q': 'Juaboso',
      'R': 'Shama',
      'Z': 'Wassa East',
      'L': 'Lawra'
    }
  },
  'U': {
    'region': 'Upper East',
    'districts': {
      '2': 'North Gonja',
      '3': 'Central Gonja',
      '4': 'East Gonja',
      '5': 'West Gonja',
      '6': 'Offinso North',
      '7': 'Offinso South',
      '9': 'Bosome Freho Ext',
      'F': 'Sefwi Akontombra',
      'X': 'Wassa Amenfi East',
      'Y': 'Wassa Amenfi West',
      'V': 'Central Tongu',
      'W': 'Wassa Amenfi Central',
      'C': 'Bia East',
      'N': 'Nzema East',
      'A': 'Aowin',
      'S': 'Sekondi-Takoradi',
      'G': 'Sefwi Wiaso',
      'I': 'Ho West',
      'H': 'Ahanta West',
      'B': 'Bibiani/Anhwiaso/Bekwai',
      'T': 'Tarkwa Nsuaem',
      'E': 'Ellembelle',
      'J': 'Jomoro',
      'K': 'Keta',
      'U': 'Suaman',
      'D': 'Bia West',
      'M': 'Mpohor',
      'O': 'Bodi',
      'P': 'Prestea Huni Valley',
      'Q': 'Juaboso',
      'R': 'Shama',
      'Z': 'Wassa East',
      'L': 'Lawra'
    }
  },
  'X': {
    'region': 'Upper West',
    'districts': {
      '2': 'North Gonja',
      '3': 'Central Gonja',
      '4': 'East Gonja',
      '5': 'West Gonja',
      '6': 'Offinso North',
      '7': 'Offinso South',
      '9': 'Bosome Freho Ext',
      'F': 'Sefwi Akontombra',
      'X': 'Wassa Amenfi East',
      'Y': 'Wassa Amenfi West',
      'V': 'Central Tongu',
      'W': 'Wassa Amenfi Central',
      'C': 'Bia East',
      'N': 'Nzema East',
      'A': 'Aowin',
      'S': 'Sekondi-Takoradi',
      'G': 'Sefwi Wiaso',
      'I': 'Ho West',
      'H': 'Ahanta West',
      'B': 'Bibiani/Anhwiaso/Bekwai',
      'T': 'Tarkwa Nsuaem',
      'E': 'Ellembelle',
      'J': 'Jomoro',
      'K': 'Keta',
      'U': 'Suaman',
      'D': 'Bia West',
      'M': 'Mpohor',
      'O': 'Bodi',
      'P': 'Prestea Huni Valley',
      'Q': 'Juaboso',
      'R': 'Shama',
      'Z': 'Wassa East',
      'L': 'Lawra'
    }
  },
  'V': {
    'region': 'Volta',
    'districts': {
      '2': 'North Gonja',
      '3': 'Central Gonja',
      '4': 'East Gonja',
      '5': 'West Gonja',
      '6': 'Offinso North',
      '7': 'Offinso South',
      '9': 'Bosome Freho Ext',
      'F': 'Sefwi Akontombra',
      'X': 'Wassa Amenfi East',
      'Y': 'Wassa Amenfi West',
      'V': 'Central Tongu',
      'W': 'Wassa Amenfi Central',
      'C': 'Bia East',
      'N': 'Nzema East',
      'A': 'Aowin',
      'S': 'Sekondi-Takoradi',
      'G': 'Sefwi Wiaso',
      'I': 'Ho West',
      'H': 'Ahanta West',
      'B': 'Bibiani/Anhwiaso/Bekwai',
      'T': 'Tarkwa Nsuaem',
      'E': 'Ellembelle',
      'J': 'Jomoro',
      'K': 'Keta',
      'U': 'Suaman',
      'D': 'Bia West',
      'M': 'Mpohor',
      'O': 'Bodi',
      'P': 'Prestea Huni Valley',
      'Q': 'Juaboso',
      'R': 'Shama',
      'Z': 'Wassa East',
      'L': 'Lawra'
    }
  },
  'W': {
    'region': 'Western',
    'districts': {
      '2': 'North Gonja',
      '3': 'Central Gonja',
      '4': 'East Gonja',
      '5': 'West Gonja',
      '6': 'Offinso North',
      '7': 'Offinso South',
      '9': 'Bosome Freho Ext',
      'F': 'Sefwi Akontombra',
      'X': 'Wassa Amenfi East',
      'Y': 'Wassa Amenfi West',
      'V': 'Central Tongu',
      'W': 'Wassa Amenfi Central',
      'C': 'Bia East',
      'N': 'Nzema East',
      'A': 'Aowin',
      'S': 'Sekondi-Takoradi',
      'G': 'Sefwi Wiaso',
      'I': 'Ho West',
      'H': 'Ahanta West',
      'B': 'Bibiani/Anhwiaso/Bekwai',
      'T': 'Tarkwa Nsuaem',
      'E': 'Ellembelle',
      'J': 'Jomoro',
      'K': 'Keta',
      'U': 'Suaman',
      'D': 'Bia West',
      'M': 'Mpohor',
      'O': 'Bodi',
      'P': 'Prestea Huni Valley',
      'Q': 'Juaboso',
      'R': 'Shama',
      'Z': 'Wassa East',
      'L': 'Lawra'
    }
  }
};